// <auto-generated />
namespace OATKWfpApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Step3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Step3));
        
        string IMigrationMetadata.Id
        {
            get { return "202204130657562_Step3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
